apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: eck-stack
    repoURL: https://helm.elastic.co
    targetRevision: 0.3.0 # Supported versions: Kubernetes 1.21-1.25
    helm:
      releaseName: eck-stack
      skipCrds: true
      values: |
        eck-elasticsearch:
          enabled: true
          annotations:
            eck.k8s.elastic.co/license: basic
          fullnameOverride: elasticsearch
          version: 8.5.0
          nodeSets:
          - name: default
            count: 1
            config:
              node.store.allow_mmap: false
            volumeClaimTemplates:
            - metadata:
                name: elasticsearch-data
              spec:
                storageClassName: nfs-share
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 30Gi
          network.host: 0.0.0.0
          xpack.security.enabled: true
        eck-kibana:
          enabled: true
          annotations:
            eck.k8s.elastic.co/license: basic
          fullnameOverride: kibana
          version: 8.5.0
          spec:
            count: 1
            elasticsearchRef:
              name: elasticsearch
            spec:
              http:
                tls:
                  selfSignedCertificate:
                    disabled: true
            podTemplate:
              spec:
                containers:
                - name: kibana
                  env:
                    - name: NODE_OPTIONS
                      value: "--max-old-space-size=2048"
                  resources:
                    requests:
                      memory: 1Gi
                      cpu: 0.5
                    limits:
                      memory: 2.5Gi
                      cpu: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true