apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: eck-stack
    repoURL: https://helm.elastic.co
    targetRevision: 0.3.0
    helm:
      releaseName: eck-stack
      skipCrds: true
      values: |
        eck-elasticsearch:
          enabled: true
          annotations:
            eck.k8s.elastic.co/license: basic
        eck-kibana:
          enabled: true
          annotations:
            eck.k8s.elastic.co/license: basic
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true