apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      releaseName: elasticsearch
      skipCrds: true
      values: |
        replicas: 3
        minimumMasterNodes: 2
        secret:
          enabled: true
          password: "elastic"
          volumeClaimTemplates:
            storageClassName: nfs-share
            accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true