apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.52.3
    helm:
      releaseName: grafana
      values: |
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki-stack.logging:3100/
            access: proxy
            jsonData:
              maxLines: 1000
          - name: Tempo
            type: tempo
            url: http://tempo-distributed.tracing:3200/
            access: proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true