apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.52.3
    helm:
      releaseName: grafana
      values: |
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki-stack.logging:3100/
            access: proxy
            jsonData:
              maxLines: 1000
          - name: Tempo
            type: tempo
            url: http://tempo-distributed.tracing:3200/
            access: proxy
            jsonData:
              httpMethod: GET
              tracesToLogs:
                datasourceUid: 'loki'
                tags: ['job', 'instance', 'pod', 'namespace']
                mappedTags: [{ key: 'service.name', value: 'service' }]
                mapTagNamesEnabled: false
                spanStartTimeShift: '1h'
                spanEndTimeShift: '1h'
                filterByTraceID: false
                filterBySpanID: false
              tracesToMetrics:
                datasourceUid: 'prom'
                tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
                queries:
                  - name: 'Sample query'
                    query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
              serviceMap:
                datasourceUid: 'prometheus'
              search:
                hide: false
              nodeGraph:
                enabled: true
              lokiSearch:
                datasourceUid: 'loki'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true