apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: jaeger-operator
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.40.0
    helm:
      releaseName: jaeger-operator
      skipCrds: true
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: jaeger
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.67.6
    helm:
      releaseName: jaeger
      skipCrds: true
      values: |
        storage:
          type: elasticsearch
          elasticsearch:
            host: elasticsearch-es-http.logging.svc.cluster.local
            port: 9200
            scheme: https
            user: elastic
            password: elastic
        provisionDataStore:
          cassandra: false
          elasticsearch: false
        query:
          cmdlineParams:
            es.tls.ca: "/tls/es.pem"
          extraConfigmapMounts:
            - name: elasticsearch-es-http-certs-public
              mountPath: /tls
              subPath: ""
              configMap: elasticsearch-es-http-certs-public
              readOnly: true
        collector:
          cmdlineParams:
            es.tls.ca: "/tls/es.pem"
          extraConfigmapMounts:
            - name: elasticsearch-es-http-certs-public
              mountPath: /tls
              subPath: ""
              configMap: elasticsearch-es-http-certs-public
              readOnly: true
        spark:
          enabled: true
          cmdlineParams:
            java.opts: "-Djavax.net.ssl.trustStore=/tls/trust.store -Djavax.net.ssl.trustStorePassword=changeit"
          extraConfigmapMounts:
            - name: elasticsearch-es-http-certs-public
              mountPath: /tls
             subPath: ""
              configMap: elasticsearch-es-http-certs-public
              readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true