apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: jaeger-operator
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.40.0
    helm:
      releaseName: jaeger-operator
      skipCrds: true
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: jaeger
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.67.6
    helm:
      releaseName: jaeger
      skipCrds: true
      values: |
        storage:
          type: elasticsearch
          elasticsearch:
            host: 192.168.11.144
            port: 9200
            scheme: https
            user: elastic
            password: elastic
        provisionDataStore:
          cassandra: false
          elasticsearch: false
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true