apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  namespace: elastic-system
spec:
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: eck-stack-eck-kibana
  type: LoadBalancer
  loadBalancerIP: 192.168.11.143