apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  namespace: elastic-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: server
  - name: https
    port: 443
    protocol: TCP
    targetPort: server
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
  type: LoadBalancer
  loadBalancerIP: 192.168.11.143