apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.24.1
    helm:
      releaseName: opentelemetry-operator
      skipCrds: true
      values:
        config:
          receivers:
            otlp:
              protocols:
                http:
                  endpoint: demo.tracing.svc.cluster.local
          processors:
          exporters:
            jaeger:
             endpoint: jaeger-collector.tracing.svc.cluster.local:14250
              tls:
                insecure: true
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: []
                exporters: [jaeger]
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.49.1
    helm:
      releaseName: opentelemetry-collector
      skipCrds: true
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: opentelemetry-demo
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.19.4
    helm:
      releaseName: opentelemetry-demo
      skipCrds: true
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true