apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: otel
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.49.1
    helm:
      releaseName: otel
      skipCrds: true
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true