- name: Install the package
  apt:
    name:
    - nfs-kernel-server
    - nfs-common

- name: Create folder
  file:
    path: "/mnt/share"
    state: directory
    mode: "777"

- name: set /etc/exports
  lineinfile:
    dest: /etc/exports
    insertafter: EOF
    line: '{{ item }}'
  with_items:
  - '/mnt/share 192.168.0.0/16(rw,no_root_squash)'
  ignore_errors: yes

- name: set fstab
  lineinfile:
    dest: /etc/fstab
    insertafter: EOF
    line: '{{ item }}'
  with_items:
  - '192.168.11.99:/mnt/nfsshare/k8s/share /mnt/share nfs defaults 0 0'

- name: mount
  shell: mount -a

- name: Enabled and Restarted nfs
  systemd:
    name: nfs-server
    state: restarted
    enabled: yes
  ignore_errors: yes